### PR TITLE
Implement chatbot functionality using Streamlit

### PR DESCRIPTION
**Pull request by JamePeng**
This commit adds the implementation of a chatbot using Streamlit, a Python library for building interactive web applications. The chatbot allows users to interact with an AI assistant, asking questions and receiving responses in real-time. 

Features include:
- Integration with the MiniCPM-V-2.0 model for generating responses.
- User-friendly interface with text input for questions and options for uploading images.
- Sidebar settings for adjusting parameters such as max_length, top_p, and temperature.
- Ability to clear chat history to start a new conversation.

The chat history and session state are managed using Streamlit's session_state functionality, ensuring a seamless user experience across interactions.

This implementation provides a simple and intuitive way for users to engage with the chatbot, making it accessible for various use cases.

### CODE REVIEW

**Comment by JamePeng** [comment]
Update MiniCPM-Llama3-V-2_5 streamlit demo

**Comment by iceflame89** [comment]
Thanks for your contribution，we will review this PR soon.

**Comment by TaiTaiTai777** [comment]
Implementing a chatbot using Streamlit is an excellent way to leverage the power of AI models for real-time interaction. Below is a step-by-step guide to set up a basic chatbot using Streamlit and the MiniCPM-V-2.0 model. We'll include features such as a text input for questions, options for uploading images, and sidebar settings for adjusting chatbot parameters.

### Prerequisites

1. **Python**: Make sure you have Python installed. Streamlit is compatible with Python 3.6 - 3.9.
2. **Libraries**: Install the necessary libraries.
    ```bash
    pip install streamlit transformers
    ```

### Step-by-Step Implementation

1. **Initialize a Streamlit App**: Create a new Python file, e.g., `chatbot.py`.

2. **Import Libraries**:
    ```python
    import streamlit as st
    from transformers import pipeline
    ```

3. **Load the Model**:
    ```python
    @st.cache(allow_output_mutation=True)
    def load_model():
        return pipeline("text-generation", model="MiniCPM-V-2.0")

    model = load_model()
    ```

4. **Create Sidebar Settings**:
    ```python
    st.sidebar.title("Settings")
    max_length = st.sidebar.slider("Max Length", 50, 500, 150)
    top_p = st.sidebar.slider("Top P", 0.5, 1.0, 0.9)
    temperature = st.sidebar.slider("Temperature", 0.5, 1.0, 0.7)
    ```

5. **Define Chat Functionality**:
    ```python
    st.title("Streamlit Chatbot")
    
    if 'history' not in st.session_state:
        st.session_state.history = []

    def clear_history():
        st.session_state.history = []
    
    st.button("Clear Chat", on_click=clear_history)

    user_input = st.text_input("You: ", "")
    if user_input:
        st.session_state.history.append({"user": user_input})
    
        response = model(user_input, max_length=max_length, top_p=top_p, temperature=temperature)[0]['generated_text']
        st.session_state.history.append({"bot": response})
    
    if st.session_state.history:
        for interaction in st.session_state.history:
            if "user" in interaction:
                st.write(f"You: {interaction['user']}")
            if "bot" in interaction:
                st.write(f"Bot: {interaction['bot']}")
    ```

6. **Run the Streamlit App**:
    ```bash
    streamlit run chatbot.py
    ```

### Optional: Image Upload Functionality

1. **Update the Sidebar for Image Upload**:
    ```python
    st.sidebar.file_uploader("Upload an image", type=["png", "jpg", "jpeg"])
    ```

2. **Process the Uploaded Image**:
    (Assuming integration with MiniCPM-V-2.0 supports image processing, otherwise, just show the image)
    ```python
    uploaded_file = st.sidebar.file_uploader("Upload an image", type=["png", "jpg", "jpeg"])

    if uploaded_file is not None:
        st.sidebar.image(uploaded_file, caption="Uploaded Image.")
        st.write("The bot currently supports text-based input. Image processing coming soon!")
    ```

### Conclusion

By following these steps, you have implemented a basic chatbot using Streamlit with a user-friendly interface. The chatbot can handle text inputs and generate responses using the MiniCPM-V-2.0 model. Additionally, sidebar settings allow users to customize the chatbot behavior, and session state management ensures a seamless user experience across multiple interactions.

Remember to check the documentation for any specific integration details or updates related to the MiniCPM-V-2.0 model and its compatibility with Streamlit.

Happy coding!

**Comment by YuzaChongyi** [comment]
Thanks for your contribution. There are several questions:
- It seems that multi-turn conversation is not implemented, because I noticed that the answers are not added to history msgs?
- Sampling decoding also supports `top_k` and `repetition_penalty`. You can add  these parameters  in sidebar. [ref](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5/blob/main/modeling_minicpmv.py#L431-L435)
- v2.5 now supports streaming output, can this be added? Only add `stream=True` in `model.chat`. [ref](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5#usage)

**Comment by JamePeng** [comment]
Done！
This update, based on the May 25, 2024 version of modeling_minicpmv.py, includes the following enhancements:

1. Introduction of repetition_penalty and top_k parameters to the st.sidebar, enabling users to adjust these model parameters dynamically.
2. Default support for stream=True in the model.chat method to facilitate real-time streaming responses.

Additionally, I feel that multi-turn conversations may not be very important. The chat_history array is currently used only to display the conversation history on the Streamlit interface. Essentially, the code can maintain continuous interaction based on the last image. The historical text from multi-turn conversations might interfere with the model's ability to express information accurately for various images shown before and after.

**Pull request merged**
